name: build-and-release
on:
    push:
        tags:
            - "*"
        paths-ignore:
            - "**.md"

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            # setup
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - name: Reconfigure git
              run: |
                  git config user.email "builder@barchart.com"
                  git config user.name "Barchart Builder"
                  git config --global url.https://${{ secrets.API_TOKEN_GITHUB }}@github.com/.insteadOf ssh://git@github.com/

            - name: Build library
              run: |
                  yarn
                  yarn build:clear
                  yarn build:ts
                  yarn build:node
                  yarn build:types
                  ls -al dist
                  echo $GITHUB_REF_NAME

            - name: Publish new build
              run: |
                  yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
