name: build-and-release
on:
    push:
        tags:
            - "build-*"
        paths-ignore:
            - "**.md"

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            # setup
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Reconfigure git
              run: |
                  git config user.email "builder@barchart.com"
                  git config user.name "Barchart Builder"
                  git config --global url.https://${{ secrets.API_TOKEN_GITHUB }}@github.com/.insteadOf ssh://git@github.com/

            - name: Build library
              run: |
                  yarn
                  yarn build:clear
                  yarn build:ts
                  yarn build:node
                  yarn build:types
                  ls -al dist
                  echo $GITHUB_REF_NAME

            - name: Publish new build
              run: |
                  export BN="artifacts"
                  export RELEASE_TAG=${GITHUB_REF_NAME:6}
                  git checkout --orphan $BN
                  echo "*\n\!.gitignore\n\!dist/*" > ./.gitignore
                  git commit -m "Automated build (tag $GITHUB_REF_NAME)"
                  git tag -a "$RELEASE_TAG" -m "$RELEASE_TAG"
                  git push origin "$RELEASE_TAG"
                  git push --delete origin "$GITHUB_REF_NAME"
